config/routes.rb
Thiggle::Application.routes.draw do
  devise_for :admins

  get "home/index"

  devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }, :controllers => {:confirmations => "confirmations"}
  
  resources :posts
  resources :conversations, only: [:index, :show, :new, :create] do
      member do
        post :reply
        post :trash
        post :untrash
      end
    end
  resources :home do
    collection do
      get :index
      get :dashboard
    end
  end

  resources :dashboard do
    collection do
      get :index
      get :my_posts
      get :saved_posts
      get :account
      get :mailbox
    end
  end

  resources :posts
  
  resources :comments

  get 'tags/:tag', to: 'posts#index', as: :tag
  resources :posts
  
  match 'user_root' => redirect("/dashboard/account")

  root :to => 'posts#index'
  

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
  	@conversations = current_user.mailbox.inbox.page(params[:page]).per(9)
    respond_to do |format|
	  format.html { render @conversations if request.xhr? }
    end
  end

  def mailbox
   	@conversations = current_user.mailbox.inbox.page(params[:page]).per(9)
    respond_to do |format|
	  format.html { render @conversations if request.xhr? }
    end
  end 	

  def my_posts
    @posts = current_user.posts
    respond_to do |format|
    format.html { render @posts if request.xhr? }
    end
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
	def time_or_date(date)
  		date.today? ? date.strftime('Today at %l:%M %p') : date.strftime('%b %d')
	end

	def to_date(date)
		date.strftime('%-m/%d/%y')
	end

end

app/views/dashboard/account.html.erb
<ul class="nav nav-tabs">
  <li>
    <%= link_to "Mailbox", mailbox_dashboard_index_path %>
  </li>
  <li><%= link_to "Selling", my_posts_dashboard_index_path %></li>
  <li><%= link_to "Saved", saved_posts_dashboard_index_path %></li>
  <li class= "active"><%= link_to "Account", account_dashboard_index_path %></li>
</ul>

<div style="margin-left:100px">
<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }) do |f| %>
  <%= devise_error_messages! %>

  <div><%= f.label :username %><br />
  <%= f.text_field :username, :autofocus => true %></div>

  <div><%= f.label :email %><br />
  <%= f.email_field :email%></div>

  <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
    <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
  <% end %>

  <div><%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
  <%= f.password_field :password, :autocomplete => "off" %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></div>

  <div><%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
  <%= f.password_field :current_password %></div>

  <div><%= f.submit "UPDATE", :class => "button-small green_normal rounded3" %></div>
<% end %>


<p><%= button_to "DELETE ACCOUNT", registration_path(resource_name), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => "button-small red_normal rounded3" %></p>

<%= link_to "Back", :back %>
</div>

</div>

<script type="text/javascript" language="javascript">
$('input#user_username').val("<%= current_user.username %>")
$('input#user_email').val("<%= current_user.email %>")

</script>

app/views/dashboard/index.html.erb
<ul class="nav nav-tabs">
  <li class = "active"><%= link_to "Profile", dashboard_index_path %></li>
  <li>
    
    <%= link_to "Mailbox", mailbox_dashboard_index_path %>
  </li>
  <li><%= link_to "Selling", my_posts_dashboard_index_path %></li>
  <li><%= link_to "Saved", saved_posts_dashboard_index_path %></li>
  <li><%= link_to "Account", account_dashboard_index_path %></li>
</ul>

<div style="margin-left: 100px">
Username : <%= current_user.username%></br>
Rep: <%= current_user.rep%></br>
Date Joined: <%= to_date(current_user.created_at)%></br>
Seen: <%= time_or_date(current_user.last_sign_in_at)%></br>
</div>

  









app/views/dashboard/mailbox.html.erb
<ul class="nav nav-tabs">
  <li class="active">
    
    <%= link_to "Mailbox", mailbox_dashboard_index_path %>
  </li>
  <li><%= link_to "Selling", my_posts_dashboard_index_path %></li>
  <li><%= link_to "Saved", saved_posts_dashboard_index_path %></li>
  <li><%= link_to "Account", account_dashboard_index_path %></li>
</ul>


		<div class="container">

	
	<table class="table">
		<h3>Inbox <%= @number_unread_messages%></h3>
    <tr>
      <th>From</th>
      <th>Subject</th>
      <th>Sent </th>
  </tr>
	<% @conversations.each do |c| %>
	<% if c.is_unread?(current_user) %>
  <tr class = "warning">
    <td><%= c.last_sender.username %></td>
	<td><b><%= link_to c.subject, c%></b></td>
	<td><%= time_or_date(c.last_message.created_at) %></td>
  </tr>
  	<% end %>
	<% if c.is_read?(current_user) %>  <tr>
    <td><%= c.last_sender.username %></td>
	<td><%= link_to c.subject, c%></td>
	<td><%= time_or_date(c.last_message.created_at) %></td>
  </tr>
  <% end %>
<% end %>
</table>
<%= paginate @conversations %>
<%= link_to "New Message", new_conversation_path%>
<br />
</div>

app/views/dashboard/my_posts.html.erb
<ul class="nav nav-tabs">

  <li>
    
    <%= link_to "Mailbox", mailbox_dashboard_index_path %>
  </li>
  <li class= "active"><%= link_to "Selling", my_posts_dashboard_index_path %></li>
  <li><%= link_to "Saved", saved_posts_dashboard_index_path %></li>
  <li><%= link_to "Account", account_dashboard_index_path %></li>
</ul>

		<div class="container">

	<table class="table">
		<h3>My Posts</h3>
    <tr>
      <th>Title</th>
  </tr>
	<% @posts.each do |p| %>
	<tr>
	<td><%=link_to p.title, "/posts/#{p.id}"%></td>
</tr>
	<% end %>

</table>
</div>

app/views/dashboard/saved_posts.html.erb
<ul class="nav nav-tabs">
  <li>
    <%= link_to "Mailbox", mailbox_dashboard_index_path %>
  </li>
  <li><%= link_to "Selling", my_posts_dashboard_index_path %></li>
  <li class= "active"><%= link_to "Saved", saved_posts_dashboard_index_path %></li>
  <li><%= link_to "Account", account_dashboard_index_path %></li>
</ul>