config/routes.rb
Thiggle::Application.routes.draw do
  devise_for :admins

  get "home/index"

  devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }, :controllers => {:confirmations => "confirmations"}
  
  resources :posts
  resources :conversations, only: [:index, :show, :new, :create] do
      member do
        post :reply
        post :trash
        post :untrash
      end
    end
  resources :home do
    collection do
      get :index
      get :dashboard
    end
  end

  resources :dashboard do
    collection do
      get :index
      get :my_posts
      get :saved_posts
      get :account
      get :mailbox
    end
  end

  resources :posts
  
  resources :comments

  get 'tags/:tag', to: 'posts#index', as: :tag
  resources :posts
  
  match 'user_root' => redirect("/dashboard/account")

  root :to => 'posts#index'
  

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user  
  has_one :user
  has_many :comments, :dependent => :destroy
  has_attached_file :photo, { 
    :styles => { 
      :medium => "1024x768", 
      :thumb => "160x160#"
      },
    :convert_options => {
      :thumb => "-quality 75 -strip -gravity center"
    }
    }
  has_attached_file :photo2, { :styles => { :medium => "1024x768", :thumb => "160x160#"}, :convert_options => {
      :thumb => "-quality 75 -strip" } }
  has_attached_file :photo3, { :styles => { :medium => "1024x768", :thumb => "160x160#"}, :convert_options => {
      :thumb => "-quality 75 -strip" } }
  has_attached_file :photo4, { :styles => { :medium => "1024x768", :thumb => "160x160#"}, :convert_options => {
      :thumb => "-quality 75 -strip" } }
  has_attached_file :photo5, { :styles => { :medium => "1024x768", :thumb => "160x160#"}, :convert_options => {
      :thumb => "-quality 75 -strip" } }
  acts_as_taggable
  paginates_per 2
  attr_accessible :category, :description, :location, :price, :title, :user_id, :created_at, :photo, :photo2, :photo3, :photo4, :photo5, :tag_list, :post_id, :posts, :street

  searchable do
    text :title, :description
    string :category
    time :created_at
    integer :price
    string :location
  end

  
  validates :title, :description, :category, :photo, :presence => true
  #validates :user_id, :numericality => {:greater_than_or_equal_to => 1}
  validates_length_of :description, :minimum => 5, :maximum => 2200
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_size :photo2, :less_than => 5.megabytes
  validates_attachment_size :photo3, :less_than => 5.megabytes
  validates_attachment_size :photo4, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => /image/
  validates_attachment_content_type :photo2, :content_type => /image/ 
  validates_attachment_content_type :photo3, :content_type => /image/ 
  validates_attachment_content_type :photo4, :content_type => /image/  
  

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  

  
  def index
    @query_string = ""
    if params[:q]
      @query_string = params[:q].strip
    end

    @search = Post.search do
      if params[:q].present?
        fulltext params[:q]
        with(:created_at).less_than Time.zone.now
      end
      if params[:cat].present? 
        with(:category).equal_to(params[:cat])
      end
      
      if params[:min].present?
        with(:price).greater_than_or_equal_to(params[:min])
      end
      if params[:max].present?
        with(:price).less_than_or_equal_to(params[:max])
      end
      if params[:loc].present?
        with(:location).equal_to(params[:loc])
      end
      order_by :created_at, :desc
      paginate :page => params[:page], :per_page => 30
    end
    @posts = @search.results

    if params[:tag]
      @posts = Post.tagged_with(params[:tag]).page(params[:page]).per(5)
    end

    #@posts = Post.order(:created_at).page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
    
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @post_user = User.find(@post.user_id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new

    @post = Post.new
    


    respond_to do |format|

      format.html # new.html.erb
      format.json { render json: @post }
      end

  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    @user = User.new(params[:user])
  #  @post.date = Time.now
    if user_signed_in? 
      @post.user_id = current_user.id
    else 
      @post.user_id = 0
    end
    
    User.find(@post.user_id).update_attributes(:rep => (current_user.rep + 10))



    respond_to do |format|
      if @post.save
        format.html { redirect_to @post}
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    
    query_string = params[:q]    

    @search = Post.search do
      keywords(query_string)
    end

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<script>
var counter = 1;
var numBoxes = 4;
function toggle4(showHideDiv) {
       var ele = document.getElementById(showHideDiv + counter);
       if(ele.style.display == "block") {
              ele.style.display = "none";
       }
       else {
              ele.style.display = "block";
       }
       if(counter == numBoxes) {
                document.getElementById("toggleButton").style.display = "none";
       }
}
</script>

<div class = "span2"> </div>
<div class= "container well">
  <%= bootstrap_form_for(@post, html: { class: 'form-horizontal' }, help: :block) do |f| %>
    <%= f.alert_message "You need to give us more information" %>

    <%= f.text_field :title, label: 'Title' %>
    <%= f.text_field :price, prepend: '$', label: 'Price', :class => "span1" %>
   
    <%= f.select :location, ["city of chicago", "north chicago", "south chicago", "west chicago", "northwest suburbs", "northwest indiana" ] %>
    <%= f.text_field :street, label: "Street or Intersection (Optional)" %>
    <%= f.select :category, ["Antiques", "Art", "Baby", "Auto Parts", "Books", "Bicycles", "Boats", "Automobiles", "Cellphones", "Clothing & Accesories", "Collectibles", "Computers", "Electronics", "Furniture", "Garage & Estate Sales", "Health & Beauty", "Jewelery", "Musical Instruments", "Sporting Goods", "Tickets", "Tools", "Toys & Games" ] %>
    <%= f.text_area :description, label: 'Description', :rows => 8, :cols => 40 %> <p class= "offset7" id="count">

    <p id="count"></p>


    <%= f.file_field :photo %>
    <div><input id="toggleButton" type="button" value="ADD ADDITIONAL PHOTOS" onclick="counter++; toggle4('photo');" class = "pull-right button-small blue_normal rounded3"></div>
    <div id = "photo2" style = "display: none;"><%= f.file_field :photo2 %></div>
    <div id = "photo3" style = "display: none;"><%= f.file_field :photo3 %></div>
    <div id = "photo4" style = "display: none;"><%= f.file_field :photo4 %></div>

    <%= f.text_field :tag_list, label: "Tags    (separated by commas)" %>

    <div class="actions">
      <%= f.submit 'SUBMIT', :class => 'button-small blue_normal rounded3' %>
    </div>
    </div>
  <% end %>


 
<script>
maxCharacters = 200;

$('#count').text(maxCharacters + " Characters Left");

$('textarea').bind('keyup keydown', function() {
    var count = $('#count');
    var characters = $(this).val().length;

    if (characters > maxCharacters) {
        count.addClass('over');
    } else {
        count.removeClass('over');
    }

    count.text(maxCharacters - characters + " Characters Left");
});


</script>

app/views/posts/_form_register.html.erb
<script>
var counter = 1;
var numBoxes = 4;
function toggle4(showHideDiv) {
       var ele = document.getElementById(showHideDiv + counter);
       if(ele.style.display == "block") {
              ele.style.display = "none";
       }
       else {
              ele.style.display = "block";
       }
       if(counter == numBoxes) {
                document.getElementById("toggleButton").style.display = "none";
       }
}
</script>

<div class = "span2"> </div>
<div class= "container well">
<% resource.posts.build %>
<%= bootstrap_form_for(resource, :as => resource_name, :url => registration_path(resource_name), html: { class: 'form-horizontal' }, help: :block) do |f| %>
<%= devise_error_messages! %>
 

  

  <%= f.fields_for :posts do |post_fields| %>

    <%= post_fields.text_field :title, label: 'Title', :autofocus => true %>
    <%= post_fields.text_field :price, prepend: '$', label: 'Price', :class => "span1" %>
   
    <%= post_fields.select :location, ["city of chicago", "north chicago", "south chicago", "west chicago", "northwest suburbs", "northwest indiana" ] %>
    <%= post_fields.text_field :street, label: "Street or Intersection (Optional)" %>
    <%= post_fields.select :category, ["Antiques", "Art", "Baby", "Auto Parts", "Books", "Bicycles", "Boats", "Automobiles", "Cellphones", "Clothing & Accesories", "Collectibles", "Computers", "Electronics", "Furniture", "Garage & Estate Sales", "Health & Beauty", "Jewelery", "Musical Instruments", "Sporting Goods", "Tickets", "Tools", "Toys & Games" ] %>
    <%= post_fields.text_area :description, label: 'Description', :rows => 8, :cols => 40 %> <p class= "offset7" id="count">

    <em id="count"></em> 


    <%= post_fields.file_field :photo %>
    <div><input id="toggleButton" type="button" value="ADD ADDITIONAL PHOTOS" onclick="counter++; toggle4('photo');" class = "pull-right button-small blue_normal rounded3"></div>
    <div id = "photo2" style = "display: none;"><%= post_fields.file_field :photo2 %></div>
    <div id = "photo3" style = "display: none;"><%= post_fields.file_field :photo3 %></div>
    <div id = "photo4" style = "display: none;"><%= post_fields.file_field :photo4 %></div>
    <%= post_fields.label :tag_list, "Tags (separated by commas)"%>
    <%= post_fields.text_field :tag_list %>
   
  <%end%>

    <div>
  <%= f.text_field :username %></div>

  <div>
  <%= f.email_field :email %></div>

  <div>
  <%= f.password_field :password %></div>

  <div>
  <%= f.password_field :password_confirmation %></div>



  <div><%= f.submit "Sign up and Post", :class => 'btn' %></div>

<% end %>

<script>
maxCharacters = 200;

$('#count').text(maxCharacters + " Characters Left");

$('textarea').bind('keyup keydown', function() {
    var count = $('#count');
    var characters = $(this).val().length;

    if (characters > maxCharacters) {
        count.addClass('over');
    } else {
        count.removeClass('over');
    }

    count.text(maxCharacters - characters + " Characters Left");
});


</script>

app/views/posts/_side_search.html.erb

<form class="form-horizontal">
<fieldset>

<!-- Form Name -->

<!-- Text input-->
<li class="nav-header">Search</li>
<li>
    <input id="q" name="q" type="text" placeholder="Search" class="input-medium"></li></br>

<!-- Prepended text-->
<li class="nav-header">Search by Location</li>
<select id="loc" name="loc" class="span10"><option value="city of chicago">city of chicago</option>
<option value="north chicago" onclick=this.form.submit()>north chicago</option>
<option value="south chicago" onclick=this.form.submit()>south chicago</option>
<option value="west chicago" onclick=this.form.submit()>west chicago</option>
<option value="northwest suburbs" onclick=this.form.submit()>northwest suburbs</option>
<option value="northwest indiana" onclick=this.form.submit()>northwest indiana</option></select>
</br>

<li class="nav-header">Search by Price</li>
    Min  <div class="input-prepend" style="margin-left: 3px">
      <span class="add-on">$</span>
      <input id="min" name="min" class="input-mini" type="text">
    </div>
    </bR>    Max <div class="input-prepend">
      <span class="add-on">$</span>
      <input id="max" name="max" class="input-mini" placeholder="<%=params[:max]%>" type="text">
    </div></br>
</br><div align="center"><button id="seach-btn" name="seach-btn" class="button-small purple_light rounded3" style= "font-size:16px" >SEARCH</button></div></br>
  <div class="">
<label class="radio" for="All">
      <input type="radio" name="cat" id="" value="" onclick=this.form.submit()>
      Search all categories
    </label></br>

<!-- Multiple Radios -->
<li class="nav-header">Search by Category</li>

    <label class="radio" for="Antiques">
      <input type="radio" name="cat" id="Antiques" value="Antiques" onclick=this.form.submit()>
      Antiques
    </label></br>
    <label class="radio" for="Baby">
      <input type="radio" name="cat" id="Baby" value="Baby" onclick=this.form.submit()>
      Baby
    </label></br>
    <label class="radio" for="Auto Parts">
      <input type="radio" name="cat" id="Auto Parts" value="Auto Parts" onclick=this.form.submit()>
      Auto Parts
    </label></br>
    <label class="radio" for="Books">
      <input type="radio" name="cat" id="Books" value="Books" onclick=this.form.submit()>
      Books
    </label></br>
    <label class="radio" for="Bicycles">
      <input type="radio" name="cat" id="Bicycles" value="Bicycles" onclick=this.form.submit()>
      Bicycles
    </label></br>
    <label class="radio" for="Boats">
      <input type="radio" name="cat" id="Boats" value="Boats" onclick=this.form.submit()>
      Boats
    </label></br>
    <label class="radio" for="Cellphones">
      <input type="radio" name="cat" id="Cellphones" value="Cellphones" onclick=this.form.submit()>
      Cellphones
    </label></br>
    <label class="radio" for="cat-7">
      <input type="radio" name="cat" id="Clothing &amp; Accesories" value="Clothing &amp; Accesories" onclick=this.form.submit()>
      Clothing &amp; Accesories
    </label></br>
    <label class="radio" for="Collectible">
      <input type="radio" name="cat" id="Collectible" value="Collectible" onclick=this.form.submit()>
      Collectible
    </label></br>
    <label class="radio" for="Computers">
      <input type="radio" name="cat" id="Computers" value="Computers" onclick=this.form.submit()>
      Computers
    </label></br>
    <label class="radio" for="Electronics">
      <input type="radio" name="cat" id="Electronics" value="Electronics" onclick=this.form.submit()>
      Electronics
    </label></br>
    <label class="radio" for="Furniture">
      <input type="radio" name="cat" id="Furniture" value="Furniture" onclick=this.form.submit()>
      Furniture
    </label></br>
    <label class="radio" for="Garage &amp; Estate Sales">
      <input type="radio" name="cat" id="Garage &amp; Estate Sales" value="Garage &amp; Estate Sales" onclick=this.form.submit()>
      Garage &amp; Estate Sales
    </label></br>
    <label class="radio" for="Health &amp; Beauty">
      <input type="radio" name="cat" id="Health &amp; Beauty" value="Health &amp; Beauty" onclick=this.form.submit()>
      Health &amp; Beauty
    </label></br>
    <label class="radio" for="Jewelery">
      <input type="radio" name="cat" id="Jewelery" value="Jewelery" onclick=this.form.submit()>
      Jewelery
    </label></br>
    <label class="radio" for="Musical Instruments">
      <input type="radio" name="cat" id="Musical Instruments" value="Musical Instruments" onclick=this.form.submit()>
      Musical Instruments
    </label></br>
    <label class="radio" for="Sporting Goods">
      <input type="radio" name="cat" id="Sporting Goods" value="Sporting Goods" onclick=this.form.submit()>
      Sporting Goods
    </label></br>
    <label class="radio" for="Tickets">
      <input type="radio" name="cat" id="Tickets" value="Tickets" onclick=this.form.submit()>
      Tickets
    </label></br>
    <label class="radio" for="Tools">
      <input type="radio" name="cat" id="Tools" value="Tools" onclick=this.form.submit()>
      Tools
    </label></br>
    <label class="radio" for="Toys &amp; Games">
      <input type="radio" name="cat" id="Toys &amp; Games" value="Toys &amp; Games" onclick=this.form.submit()>
      Toys &amp; Games
    </label>
  </div>


</fieldset>
</form>

<script type="text/javascript" language="javascript">
$('input#min.input-mini').val("<%=params[:min] %>")
$('input#max.input-mini').val("<%=params[:max] %>")
$('input#q.input-medium').val(" <%= @query_string %>")
$('select#loc').val("<%= params[:loc] %>")
cat = document.getElementById("<%= params[:cat] %>")
cat.checked = true
</script>

app/views/posts/edit.html.erb
<h1>Editing post</h1>


<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<script src="/assets/jquery.cycle.all.js?body=1" type="text/javascript"></script>

<script type="text/javascript">//<![CDATA[ 
$(window).load(function(){
$(".my-link").click(function() {
    $(this).closest("div").next(".class2").toggle();
});
});//]]>  




</script>

<script type="text/javascript">//<![CDATA[ 



jQuery(function($){


    // Cycle plugin
    $('.slides').cycle({
        fx:     'none',
        speed:   500,
        timeout: 700,
        delay:  -4000,
        height:  'auto',
        fit: 1
    }).cycle("pause");
    
    

    // Pause & play on hover
    $('.slideshow-block').hover(function(){
        $(this).find('.slides').addClass('active').cycle('resume');
    }, function(){
        $(this).find('.slides').removeClass('active').cycle('pause');
    });

});

</script>



<div style="display:inline-block">
	<div class="row-fluid">
		<div>
			<div class="well sidebar-nav span3 offset1" style= "width:250px">
				<ul class="nav nav-list">
					<%= render 'side_search' %>

			</ul>
		
		</div><!--/.well -->
	</div><!--/span-->
	<div class = "span5">
		<% if flash[:notice] %>
		    <div class="alert span5">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
		    	<%= flash[:notice] %></br></div>
		  <% end %>

<!-- 		<div style= "font-size:20px">
			<b><%= @posts.count%></b> 
			<% if params[:q].present?  %>
			results for "<%=params[:q].strip %>" 
				<%else%>
				 results 
				
			<% end %>
				<% if params[:location].present? %>
				around <%= params[:location]%>
				<% end %>
				<% if params[:min].present? %>
				for at least $<%= params[:min] %> 
				<% end %>
				<% if params[:max].present?  %>
				but under $<%= params[:max] %>
				<% end %>
				<% if params[:cat].present? %>
				in <b><%=params[:cat]%></b>.
				<%else %>
				in All Categories.
				<%end %>
				</br>
			
		</div>  -->
		<%# @post = @search.results%>
		
		
		<table class = "post span5 offset1">

			<% @posts.each do |post| %>

			<tr class = "well well-small marginbottom listing" id = <%= post.id %> >
				
					<td> 
                        
                        <div class = 'thumbnail post' style= 'width: 160px'>
						<div class = "slideshow-block" style="background: url(<%= post.photo.url(:thumb) %>) no-repeat">
						
							<div class = "slides" >
           						 	<%= image_tag post.photo.url(:thumb) %>
           						  	<% if post.photo2.present? %> 
              							<%= image_tag post.photo2.url(:thumb) %>
            						<% end %>
            						<% if post.photo3.present? %> 
            							<%= image_tag post.photo3.url(:thumb) %>
           					 		<% end %>
           				  		      <% if post.photo4.present? %> 
           			   			   		<%= image_tag post.photo4.url(:thumb) %>
           		   					<% end %>
        	  					</div>
  		    				</div>
                        



					</td>
					<td class= 'listing-title' style="word-wrap: break-word"><div class= "post" style="width:400px"><%= link_to post.title, post , :class => "post-title"%></br><div style= "color:grey" >
                        <%= link_to post.category, posts_path(:q => params[:q], :min => params[:min], :max => params[:max], :cat => post.category), :style => 'color: grey;'%>


                         in <%= link_to post.location, posts_path(:q => params[:q], :min => params[:min], :max => params[:max], :cat => params[:cat], :loc => post.location), :style => 'color: grey;'%> 

                         <% if post.street.present? %> > 

                         <%= post.street %> 

                         <%end%></div><hr></div>
			
						<%= post.description %><p> <%= raw post.tag_list.map { |t| link_to "##{t}", tag_path(t) }.join(' ') %></p>

						
                        <% if user_signed_in? %>
						
						<div id = "reply">
							<div class="container">
							<div class="class1">
							<!-- <a href="#" class="my-link">Reply</a> -->
							</div>
							<div class="class2" style = "display:none">
								Ask @<%= User.find(post.user_id).username %> a question:  </br>
                                <%= form_for :comment, :controller => "comments_controller", :url => url_for(:controller => 'comments', :action => 'create') do |f| %>
								<%= f.text_field :text %>
								<%= f.hidden_field :post_id, :value => post.id %>
								<%end %>

								<% post.comments.each do |comment| %>
								<b><%= comment.user_name %></b> wrote 
								<p><%= comment.text %></p>
								<hr>

								<%end %>
							
							</div>
							</div>
							
						<%end%>
							
						
						

						<td class = "price" ><b>$<%= link_to post.price, posts_path(:min => post.price), :class => 'price', :style => 'color: black;' %></b></td></td>
				
					

				</tr>
                </div>
    			
				<% end %>
				
			</table>
		

		</div>
	</div>






	<div class= 'container'> 
        <div class= 'row-fluid'>
            <div class = "span6"> 
                <%= paginate @posts %>
            </div>
        </div>
    </div>
	<%= link_to 'New Post', new_post_path %>
</div>

<script>
$('.listing').click(function(evt) {
  //location.href= "posts/" + this.id;
  $(evt.target).children("div").find(".class2").toggle();
});

$('.listing').css('cursor','pointer');
</script>

app/views/posts/new.html.erb
<% if user_signed_in? %>

<%= render 'form' %>
<% else %>
<%= render 'form_register' %>
<% end %> 

<!-- <%= link_to 'Back', posts_path %> -->

app/views/posts/show.html.erb
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />



<table class="table" >
	<tr >
		<td colspan = 2 style="text-align: center">
			<div id="controls"></div>
			<div id="loading"></div>
			<div id="slideshow" class ="resizable"></div>
		</td>
	</tr>

	<tr >
		<td style="text-align: center">
			<div id="thumbs" class= "navigation">
				<ul class="thumbs">
					<li> 
						<a class="thumb" name="1" href="<%= @post.photo.url(:medium) %>" title="your image title">
                <%= image_tag @post.photo.url(:thumb) %>
            			</a>
        			</li>
					<% if @post.photo2.present? %>
					<li> 
						<a class="thumb" name="1" href="<%= @post.photo2.url(:medium) %>" title="your image title">
                <%= image_tag @post.photo2.url(:thumb) %>
            			</a>
        			</li>
        			<% end %>
        			<% if @post.photo3.present? %>
					<li> 
						<a class="thumb" name="1" href="<%= @post.photo3.url(:medium) %>" title="your image title">
                <%= image_tag @post.photo3.url(:thumb) %>
            			</a>
        			</li>
        			<% end %>
        			<% if @post.photo4.present? %>
        			<li> 
						<a class="thumb" name="1" href="<%= @post.photo3.url(:medium) %>" title="your image title">
                <%= image_tag @post.photo4.url(:thumb) %>
            			</a>
        			</li>
        			<% end %>

    		</div>

		</td>
		<td class="showpost">
			<div style = "font-size:22px">
			<%= @post.title %></br>
			</div>
			<%= @post.category %> in <%= @post.location %> > <%= @post.street%><hr></br>
			<%= @post.description %>

		</td>
	</tr>
</table>







<script type="text/javascript">

			jQuery(document).ready(function($) {
				// We only want these styles applied when javascript is enabled
				$('div.content').css('display', 'block');

				// Initially set opacity on thumbs and add
				// additional styling for hover effect on thumbs
				var onMouseOutOpacity = 0.67;
				$('#thumbs ul.thumbs li, div.navigation a.pageLink').opacityrollover({
					mouseOutOpacity:   onMouseOutOpacity,
					mouseOverOpacity:  1.0,
					fadeSpeed:         'fast',
					exemptionSelector: '.selected'
				});
				
				// Initialize Advanced Galleriffic Gallery
				var gallery = $('#thumbs').galleriffic({
					delay:                     2500,
					numThumbs:                 4,
					preloadAhead:              4,
					enableTopPager:            false,
					enableBottomPager:         false,
					imageContainerSel:         '#slideshow',
					controlsContainerSel:      '#controls',
					captionContainerSel:       '#caption',
					loadingContainerSel:       '#loading',
					renderSSControls:          false,
					renderNavControls:         true,
					playLinkText:              'Play Slideshow',
					pauseLinkText:             'Pause Slideshow',
					prevLinkText:              '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lsaquo; Previous Photo&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',
					nextLinkText:              '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Next Photo &rsaquo;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',
					nextPageLinkText:          '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Next &rsaquo;',
					prevPageLinkText:          '&lsaquo; Prev',
					enableHistory:             false,
					autoStart:                 false,
					syncTransitions:           false,
					defaultTransitionDuration: 700,
					onSlideChange:             function(prevIndex, nextIndex) {
						// 'this' refers to the gallery, which is an extension of $('#thumbs')
						this.find('ul.thumbs').children()
							.eq(prevIndex).fadeTo('fast', onMouseOutOpacity).end()
							.eq(nextIndex).fadeTo('fast', 1.0);

						// Update the photo index display
						this.$captionContainer.find('div.photo-index')
							.html('Photo '+ (nextIndex+1) +' of '+ this.data.length);
					},
					onPageTransitionOut:       function(callback) {
						this.fadeTo('fast', 0.0, callback);
					},
					onPageTransitionIn:        function() {
						var prevPageLink = this.find('a.prev').css('visibility', 'hidden');
						var nextPageLink = this.find('a.next').css('visibility', 'hidden');
						
						// Show appropriate next / prev page links
						if (this.displayedPage > 0)
							prevPageLink.css('visibility', 'visible');

						var lastPage = this.getNumPages() - 1;
						if (this.displayedPage < lastPage)
							nextPageLink.css('visibility', 'visible');

						this.fadeTo('fast', 1.0);
					}
				});

				/**************** Event handlers for custom next / prev page links **********************/

				gallery.find('a.prev').click(function(e) {
					gallery.previousPage();
					e.preventDefault();
				});

				gallery.find('a.next').click(function(e) {
					gallery.nextPage();
					e.preventDefault();
				});

				/****************************************************************************************/

			});
		
</script>








<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>